name: Bad CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: git clone https://github.com/user/repo.git
      
      - name: Install dependencies
        run: npm install  
      
      - name: Deploy to production
        run: |
          echo "Deploying..."
          ssh root@192.168.1.1 "cd /var/www/app && git pull" 

      - name: Run tests
        run: echo "Skipping tests..."  
      
      - name: Deploy confirmation
        run: echo "Deployment successful!"
