name: Bad CI/CD
on: 
  push:
    branches: 
      - main
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: i without cache
        run: |
          npm init -y
          npm install
      
      - name: no timeouts
        run: |
          echo "No timeouts"
          sleep 5
      
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
